import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VANDIAMS - AI Custom Jewelry",
  description: "Generated by TheCodeFolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Playfair+Display:wght@400;600&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Discover exquisite rings and jewelry at Vandiams Jewelry Store" />

        {/* <!-- Open Graph / Facebook / WhatsApp --> */}
        <meta property="og:title" content="Vandiams Jewelry Store" />
        <meta property="og:description" content="Discover exquisite rings and jewelry at Vandiams Jewelry Store" />
        <meta property="og:image" content="/logo.png" />
        <meta property="og:url" content="https://vandiams.com" />
        <meta property="og:type" content="website" />

        {/* <!-- Twitter --> */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Vandiams Jewelry Store" />
        <meta name="twitter:description" content="Discover exquisite rings and jewelry at Vandiams Jewelry Store" />
        <meta name="twitter:image" content="/logo.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
